version: "3.8"

services:

  mongo:
    image: mongo:latest
    container_name: wanderlust-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:latest
    container_name: wanderlust-redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: wanderlust-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: wanderlust-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:
