# stage 1 

FROM node:20-alpine AS builder

WORKDIR /app


COPY package*.json ./

RUN npm install --omit=dev

COPY . .


#  stage 2 


FROM node:20-alpine


WORKDIR /app


COPY --from=builder /app /app


EXPOSE 5000

CMD ["node","server.js"]
